# Global Development Environment Configuration

# Restful Booker API
restfulbooker.base.url=https://restful-booker.herokuapp.com
restfulbooker.auth.url=/auth

# ReqRes API
reqres.base.url=https://reqres.in/api
reqres.users.endpoint=/users
reqres.api.key=pub_3006d5b8b1719b6d8e75f2404f3366fb7f1893f9b7a3804f4f1064b5edcea630

# GoRest API
gorest.base.url=https://gorest.co.in/public/v2
gorest.users.endpoint=/users
gorest.auth.token=Bearer 61f22ca58528fe711f6c8d3c06eaf47168eecebb8fa25ba050d3ae76480b2e35

# Dummy Rest API
dummy.base.url=https://dummy.restapiexample.com/api/v1
dummy.employees.endpoint=/employees
dummy.employee.endpoint=/employee
dummy.create.endpoint=/create
dummy.update.endpoint=/update
dummy.delete.endpoint=/delete

# General Settings
api.connection.timeout=30000
api.logging.enabled=true
